
![logo](https://upload.wikimedia.org/wikipedia/commons/4/44/Huntsman-Wordmark-with-USU-Blue.gif#center)


---

# Python basics (20 pionts)

### Instructor: Pedram Jahangiry

---

##### 1. Import Numpy package as np

In [ ]:
# CODE HERE
import numpy as np

#####  2. Create the following numpy array using two functions:  arange() and linspace(). You must generate the same answers.

In [ ]:
np.arange(2,20,4)# Code here (using arange function)

array([ 2,  6, 10, 14, 18])

In [ ]:
# Do NOT write here!


array([ 2,  6, 10, 14, 18])

In [ ]:
np.linspace(2,18,5)# Code here (using linspace function)

array([ 2.,  6., 10., 14., 18.])

In [ ]:
# Do NOT write here!


array([ 2.,  6., 10., 14., 18.])

##### 3. Create the following matrix of ones and save it as my_matrix.

In [ ]:
my_matrix = np.linspace(1,1,16).reshape(4,4)# Code here
my_matrix

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
# Do NOT write here


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

#### 4. Reshape "my_matrix" into a new matrix as shown below.

In [ ]:
my_matrix = np.reshape(my_matrix,(2,8))# Code here
my_matrix

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
# Do NOT write here
my_matrix

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

#### 5. First, replace the first row of "my_matrix" with zeros. then replace the last column with 2s. Save the new matrix as "my_matrix2".

In [ ]:
my_matrix2 = my_matrix.reshape(4,4)
my_matrix2[0] = 0
my_matrix2[:,3] = 2
my_matrix2


array([[0., 0., 0., 2.],
       [1., 1., 1., 2.],
       [1., 1., 1., 2.],
       [1., 1., 1., 2.]])

In [ ]:
# Do not write here
my_matrix2

array([[0., 0., 0., 2.],
       [1., 1., 1., 2.],
       [1., 1., 1., 2.],
       [1., 1., 1., 2.]])

#### 6. Create the following matrix and save it as "A".

In [ ]:
A = np.linspace(.01,1.,100).reshape(10,10)# Code here
A

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [ ]:
# Do NOT write here.
A

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

##### 7. Create a 10 * 10 matrix using random values drawn from a standard normal distribution. Call this matrix "B". Set seed number = 100

In [ ]:
np.random.seed(100)
B = np.random.randn(10,10)# Code here
B

array([[-1.74976547,  0.3426804 ,  1.1530358 , -0.25243604,  0.98132079,
         0.51421884,  0.22117967, -1.07004333, -0.18949583,  0.25500144],
       [-0.45802699,  0.43516349, -0.58359505,  0.81684707,  0.67272081,
        -0.10441114, -0.53128038,  1.02973269, -0.43813562, -1.11831825],
       [ 1.61898166,  1.54160517, -0.25187914, -0.84243574,  0.18451869,
         0.9370822 ,  0.73100034,  1.36155613, -0.32623806,  0.05567601],
       [ 0.22239961, -1.443217  , -0.75635231,  0.81645401,  0.75044476,
        -0.45594693,  1.18962227, -1.69061683, -1.35639905, -1.23243451],
       [-0.54443916, -0.66817174,  0.00731456, -0.61293874,  1.29974807,
        -1.73309562, -0.9833101 ,  0.35750775, -1.6135785 ,  1.47071387],
       [-1.1880176 , -0.54974619, -0.94004616, -0.82793236,  0.10886347,
         0.50780959, -0.86222735,  1.24946974, -0.07961125, -0.88973148],
       [-0.88179839,  0.01863895,  0.23784462,  0.01354855, -1.6355294 ,
        -1.04420988,  0.61303888,  0.73620521

In [ ]:
# Do NOT write here
B

array([[-1.74976547,  0.3426804 ,  1.1530358 , -0.25243604,  0.98132079,
         0.51421884,  0.22117967, -1.07004333, -0.18949583,  0.25500144],
       [-0.45802699,  0.43516349, -0.58359505,  0.81684707,  0.67272081,
        -0.10441114, -0.53128038,  1.02973269, -0.43813562, -1.11831825],
       [ 1.61898166,  1.54160517, -0.25187914, -0.84243574,  0.18451869,
         0.9370822 ,  0.73100034,  1.36155613, -0.32623806,  0.05567601],
       [ 0.22239961, -1.443217  , -0.75635231,  0.81645401,  0.75044476,
        -0.45594693,  1.18962227, -1.69061683, -1.35639905, -1.23243451],
       [-0.54443916, -0.66817174,  0.00731456, -0.61293874,  1.29974807,
        -1.73309562, -0.9833101 ,  0.35750775, -1.6135785 ,  1.47071387],
       [-1.1880176 , -0.54974619, -0.94004616, -0.82793236,  0.10886347,
         0.50780959, -0.86222735,  1.24946974, -0.07961125, -0.88973148],
       [-0.88179839,  0.01863895,  0.23784462,  0.01354855, -1.6355294 ,
        -1.04420988,  0.61303888,  0.73620521

##### 8. Multiply matrix A and B. (use the Matrix multiplication, NOT the element-wised multiplication) 

In [ ]:
np.dot(A,B)# Code here

array([[-0.38520099,  0.06358488, -0.05722663, -0.06955691,  0.43190936,
        -0.12156679,  0.06534707,  0.02587607, -0.11242174, -0.5925726 ],
       [-0.96896951,  0.17349491, -0.17278352, -0.17456096,  1.13265468,
        -0.2713685 ,  0.18147958,  0.09578209, -0.42840209, -1.36081353],
       [-1.55273803,  0.28340494, -0.28834041, -0.279565  ,  1.8334    ,
        -0.4211702 ,  0.2976121 ,  0.16568812, -0.74438244, -2.12905447],
       [-2.13650655,  0.39331498, -0.40389731, -0.38456905,  2.53414533,
        -0.57097191,  0.41374462,  0.23559414, -1.06036278, -2.8972954 ],
       [-2.72027506,  0.50322501, -0.5194542 , -0.48957309,  3.23489065,
        -0.72077361,  0.52987714,  0.30550017, -1.37634313, -3.66553634],
       [-3.30404358,  0.61313505, -0.63501109, -0.59457714,  3.93563597,
        -0.87057532,  0.64600966,  0.37540619, -1.69232348, -4.43377727],
       [-3.8878121 ,  0.72304508, -0.75056798, -0.69958118,  4.6363813 ,
        -1.02037702,  0.76214218,  0.44531222

In [ ]:
# Do NOT write here


array([[-0.38520099,  0.06358488, -0.05722663, -0.06955691,  0.43190936,
        -0.12156679,  0.06534707,  0.02587607, -0.11242174, -0.5925726 ],
       [-0.96896951,  0.17349491, -0.17278352, -0.17456096,  1.13265468,
        -0.2713685 ,  0.18147958,  0.09578209, -0.42840209, -1.36081353],
       [-1.55273803,  0.28340494, -0.28834041, -0.279565  ,  1.8334    ,
        -0.4211702 ,  0.2976121 ,  0.16568812, -0.74438244, -2.12905447],
       [-2.13650655,  0.39331498, -0.40389731, -0.38456905,  2.53414533,
        -0.57097191,  0.41374462,  0.23559414, -1.06036278, -2.8972954 ],
       [-2.72027506,  0.50322501, -0.5194542 , -0.48957309,  3.23489065,
        -0.72077361,  0.52987714,  0.30550017, -1.37634313, -3.66553634],
       [-3.30404358,  0.61313505, -0.63501109, -0.59457714,  3.93563597,
        -0.87057532,  0.64600966,  0.37540619, -1.69232348, -4.43377727],
       [-3.8878121 ,  0.72304508, -0.75056798, -0.69958118,  4.6363813 ,
        -1.02037702,  0.76214218,  0.44531222

##### 9. Import Pandas package as pd

In [ ]:
import pandas as pd # Code here


In [ ]:
# Do Not write here


##### 10. Create a data frame with three columns A, B, C. Name your data frame as df. Again use the seed number = 100
* Column A: 20 random numbers from the uniform distribution 
* Column B: the first 20 Capitals of english letters
* Column C: range of numbers between 20 and 39 


In [64]:
my_list = []
for i in range(65,85):
 a = chr(i) #looked up the function that changed numbers into letters with ascii values
 my_list.append(a)
letter = np.array(my_list)

In [66]:
np.random.seed(100)
d = {"A" : np.random.rand(20),"B": letter, "C": np.arange(20,40)}
df = pd.DataFrame(data = d)
# df# Code here

In [67]:
df

A  B   C
0   0.543405  A  20
1   0.278369  B  21
2   0.424518  C  22
3   0.844776  D  23
4   0.004719  E  24
5   0.121569  F  25
6   0.670749  G  26
7   0.825853  H  27
8   0.136707  I  28
9   0.575093  J  29
10  0.891322  K  30
11  0.209202  L  31
12  0.185328  M  32
13  0.108377  N  33
14  0.219697  O  34
15  0.978624  P  35
16  0.811683  Q  36
17  0.171941  R  37
18  0.816225  S  38
19  0.274074  T  39

In [ ]:
# Do Not write here
df

A  B   C
0   0.543405  A  20
1   0.278369  B  21
2   0.424518  C  22
3   0.844776  D  23
4   0.004719  E  24
5   0.121569  F  25
6   0.670749  G  26
7   0.825853  H  27
8   0.136707  I  28
9   0.575093  J  29
10  0.891322  K  30
11  0.209202  L  31
12  0.185328  M  32
13  0.108377  N  33
14  0.219697  O  34
15  0.978624  P  35
16  0.811683  Q  36
17  0.171941  R  37
18  0.816225  S  38
19  0.274074  T  39

##### 11. Create a new column in df and name is as "default". If A>0.5 then default =1 otherwise 0. 

In [71]:
df["default"] = df["A"].apply(lambda x: 1 if(x>.5) else 0)# Code here #got an example on how to incorporate ifs in lambda functions
#https://sparkbyexamples.com/python/python-lambda-using-if-else/#:~:text=You%20can%20use%20the%20if%2Delse%20statement%20as%20part%20of,it%20returns%20the%20None%20value.
df

A  B   C  default
0   0.543405  A  20        1
1   0.278369  B  21        0
2   0.424518  C  22        0
3   0.844776  D  23        1
4   0.004719  E  24        0
5   0.121569  F  25        0
6   0.670749  G  26        1
7   0.825853  H  27        1
8   0.136707  I  28        0
9   0.575093  J  29        1
10  0.891322  K  30        1
11  0.209202  L  31        0
12  0.185328  M  32        0
13  0.108377  N  33        0
14  0.219697  O  34        0
15  0.978624  P  35        1
16  0.811683  Q  36        1
17  0.171941  R  37        0
18  0.816225  S  38        1
19  0.274074  T  39        0

In [ ]:
# Do Not write here
df

A  B   C  default
0   0.543405  A  20        1
1   0.278369  B  21        0
2   0.424518  C  22        0
3   0.844776  D  23        1
4   0.004719  E  24        0
5   0.121569  F  25        0
6   0.670749  G  26        1
7   0.825853  H  27        1
8   0.136707  I  28        0
9   0.575093  J  29        1
10  0.891322  K  30        1
11  0.209202  L  31        0
12  0.185328  M  32        0
13  0.108377  N  33        0
14  0.219697  O  34        0
15  0.978624  P  35        1
16  0.811683  Q  36        1
17  0.171941  R  37        0
18  0.816225  S  38        1
19  0.274074  T  39        0

# Good luck!